{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "cpu load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logstash_process_cpu_load_average_1m{hostname=\"$hostname\"}",
     "legendFormat": "load  1m"
    },
    {
     "expr": "logstash_process_cpu_load_average_5m{hostname=\"$hostname\"}",
     "legendFormat": "load  5m"
    },
    {
     "expr": "logstash_process_cpu_load_average_15m{hostname=\"$hostname\"}",
     "legendFormat": "load  15m"
    }
   ]
  },
  {
   "title": "cpu_percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logstash_process_cpu_percent{hostname=\"$hostname\"}",
     "legendFormat": "cpu_percent"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "open files",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logstash_process_open_file_descriptors{hostname=\"$hostname\"}",
     "legendFormat": "open_file_descriptors"
    },
    {
     "expr": "logstash_process_max_file_descriptors{hostname=\"$hostname\"}",
     "legendFormat": "max_file_descriptors"
    },
    {
     "expr": "logstash_process_peak_open_file_descriptors{hostname=\"$hostname\"}",
     "legendFormat": "peak_open_file_descriptors"
    }
   ]
  },
  {
   "title": "jvm gc time (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_gc_collectors_old_collection_time_in_millis{hostname=\"$hostname\"}",
     "legendFormat": "old gc (ms)"
    },
    {
     "expr": "logstash_jvm_gc_collectors_young_collection_time_in_millis{hostname=\"$hostname\"}",
     "legendFormat": "young gc (ms)"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "heap pencent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_mem_heap_used_percent{hostname=\"$hostname\"}",
     "legendFormat": "heap pencent"
    }
   ]
  },
  {
   "title": "jvm gc count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_gc_collectors_old_collection_count{hostname=\"$hostname\"}",
     "legendFormat": "old gc (ms)"
    },
    {
     "expr": "logstash_jvm_gc_collectors_young_collection_count{hostname=\"$hostname\"}",
     "legendFormat": "young gc (ms)"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "jvm_mem_pools_old",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_mem_pools_old_committed_in_bytes{hostname=\"$hostname\"}",
     "legendFormat": "old_committed_in_bytes"
    },
    {
     "expr": "logstash_jvm_mem_pools_old_max_in_bytes{hostname=\"$hostname\"}",
     "legendFormat": "old_max_in_bytes"
    },
    {
     "expr": "logstash_jvm_mem_pools_old_used_in_bytes{hostname=\"$hostname\"}",
     "legendFormat": "old_used_in_bytes"
    }
   ]
  },
  {
   "title": "jvm_mem_pools_survivor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_mem_pools_survivor_committed_in_bytes{hostname=\"$hostname\"}",
     "legendFormat": "survivor_committed_in_bytes"
    },
    {
     "expr": "logstash_jvm_mem_pools_survivor_max_in_bytes{hostname=\"$hostname\"}",
     "legendFormat": "survivor_max_in_bytes"
    },
    {
     "expr": "logstash_jvm_mem_pools_survivor_used_in_bytes{hostname=\"$hostname\"}",
     "legendFormat": "survivor_used_in_bytes"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "jvm_mem_pools_young",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_mem_pools_young_committed_in_bytes{hostname=\"$hostname\"}",
     "legendFormat": "young_committed_in_bytes"
    },
    {
     "expr": "logstash_jvm_mem_pools_young_max_in_bytes{hostname=\"$hostname\"}",
     "legendFormat": "young_max_in_bytes"
    },
    {
     "expr": "logstash_jvm_mem_pools_young_used_in_bytes{hostname=\"$hostname\"}",
     "legendFormat": "young_used_in_bytes"
    }
   ]
  },
  {
   "title": "pipeline_events count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logstash_pipeline_events_in{hostname=\"$hostname\"}",
     "legendFormat": "events_in"
    },
    {
     "expr": "logstash_pipeline_events_out{hostname=\"$hostname\"}",
     "legendFormat": "events_out"
    },
    {
     "expr": "logstash_pipeline_events_filtered{hostname=\"$hostname\"}",
     "legendFormat": "events_filtered"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "jvm_threads_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_threads_count{hostname=\"$hostname\"}",
     "legendFormat": "jvm_threads_count"
    }
   ]
  },
  {
   "title": "logstash_pipeline_events_duration_in_millis",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "logstash_pipeline_events_queue_push_duration_in_millis{hostname=\"$hostname\"}",
     "legendFormat": "events_queue_push_duration"
    },
    {
     "expr": "logstash_pipeline_events_duration_in_millis{hostname=\"$hostname\"}",
     "legendFormat": "events_duration"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "logstash_pipeline_events_duration_in_millis",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "logstash_pipeline_reloads_failures{hostname=\"$hostname\"}",
     "legendFormat": "pipeline_reloads_failures"
    }
   ]
  }
 ]
}